// Default config values. Do not edit this file.
// Create a personal copy named `config.js` to override anything you need.
// `config.js` is git-ignored so you can keep work-specific links private.

window.DASHBOARD_DEFAULT_CONFIG = {
  theme: 'auto', // 'dark' | 'light' | 'auto'
  keybinds: {
    quickLauncherOpen: 'Mod+K',
    toggleTheme: 't',
    focusGoogle: '/',
    focusGo: 'g',
    quickLauncherClose: 'Escape',
    quickLauncherNext: 'ArrowDown',
    quickLauncherPrev: 'ArrowUp',
    quickLauncherOpenInTab: 'Enter'
  },
  backgrounds: {
    // Place your images under a local `wallpapers/` folder or use full URLs
    enable: true,
    cycleMs: 15000, // time between changes
    transitionMs: 1200, // crossfade duration
    randomize: true,
    light: [
      // 'wallpapers/light/light1.jpg', 'wallpapers/light/light2.jpg'
    ],
    dark: [
      // 'wallpapers/dark/dark1.jpg', 'wallpapers/dark/dark2.jpg'
    ]
  },
  miniBrowser: {
    // Initial URL for the mini browser input and iframe
    defaultUrl: 'https://www.google.com/webhp?igu=1'
  },
  google: {
    baseUrl: 'https://www.google.com/search',
    queryParam: 'q'
  },
  go: {
    fallbackSearchUrl: 'http://go/',
  },
  sections: [
    {
      title: 'Daily',
      links: [
        { label: 'Ticket Tool', url: 'https://tickets.example.com', icon: '🎫' },
        { label: 'GitHub Copilot', url: 'https://github.com/copilot', icon: '🤖' },
        { label: 'Outlook', url: 'https://outlook.office.com/mail', icon: '📧' }
      ]
    },
    {
      title: 'System Admin Pages',
      links: [
        { label: 'Admin Console', url: 'https://admin.example.com', icon: '🛠️' }
      ]
    },
    {
      title: 'Other Pages',
      links: [
        { label: 'Company Wiki', url: 'https://wiki.example.com', icon: '📚' }
      ]
    }
  ]
};


