// Default config values. Do not edit this file.
// Create a personal copy named `config.js` to override anything you need.
// `config.js` is git-ignored so you can keep work-specific links private.

window.DASHBOARD_DEFAULT_CONFIG = {
  theme: 'auto', // 'dark' | 'light' | 'auto'
  google: {
    baseUrl: 'https://www.google.com/search',
    queryParam: 'q'
  },
  go: {
    // Where to go for a bare `go/`
    homepageUrl: 'https://go/',
    // If provided, unknown keys will open this URL + encoded key
    // e.g. 'https://go/search?q='
    fallbackSearchUrl: '',
    // Map short keys to full URLs (case-insensitive)
    keyToUrl: {
      PAM: 'https://intranet.example.com/pam'
    }
  },
  sections: [
    {
      title: 'Daily',
      links: [
        { label: 'Ticket Tool', url: 'https://tickets.example.com', icon: '🎫' },
        { label: 'GitHub Copilot', url: 'https://github.com/copilot', icon: '🤖' },
        { label: 'Outlook', url: 'https://outlook.office.com/mail', icon: '📧' }
      ]
    },
    {
      title: 'System Admin Pages',
      links: [
        { label: 'Admin Console', url: 'https://admin.example.com', icon: '🛠️' }
      ]
    },
    {
      title: 'Other Pages',
      links: [
        { label: 'Company Wiki', url: 'https://wiki.example.com', icon: '📚' }
      ]
    }
  ]
};


